name: Publish VS Code Extension

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Clean & Install dependencies
        run: |
          npm cache clean --force
          npm ci

      - name: Install CLI tools
        run: npm install --no-save @vscode/vsce ovsx

      - name: Package extension
        run: npx vsce package

      - name: Publish to VSCE
        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Publish to Open VSX
        run: npx ovsx publish -p ${{ secrets.OVSX_TOKEN }}
